version: "3"
services:
  bot:
    deploy:
      resources:
        limits:
          memory: 256M
    env_file:
      - .env
    build:
      context: ./
      dockerfile: Dockerfile
    command: sh -c "python -m pip install -r requirements.txt && python main.py"